### ISSUE TITLE
Make it work on Python 3.10

### ISSUE THREAD

**Issue by jwg4** [jwg4/flask-selfdoc#61]
Currently fails because of:
ImportError: cannot import name 'MutableMapping' from 'collections'

**Comment by ValentinFrancois** [comment]
https://github.com/jwg4/flask-selfdoc/pull/72 closes this, right?
